# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('locLat', models.FloatField(default=0)),
                ('locLng', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
