# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_remove_cafe_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='Roastery',
            field=models.CharField(default='N', max_length=5),
            preserve_default=False,
        ),
    ]
