# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_cafe_roastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='Roastery',
            field=models.CharField(default='N', max_length=5),
        ),
    ]
