# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20161204_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
