# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20161204_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='Engname',
            field=models.CharField(default='Engname', max_length=10),
            preserve_default=False,
        ),
    ]
